version: '2.1'
services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=surveystream
    volumes:
      - ../tests/unit/data/launch_local_db/data:/docker-entrypoint-initdb.d/data
    ports:
      - "5433:5433"
    command:
      -p 5433
  api:
    image: ${BACKEND_NAME}:${VERSION}
    environment:
      - CONFIG_TYPE=app.config.ProfilingConfig
      - PYTHONUNBUFFERED=0
      - AWS_REGION=ap-south-1
      - ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
    volumes:
      - ../profiling/outputs:/usr/src/${BACKEND_NAME}/profiling/outputs
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["/bin/bash","-c"]
    command:
    - |
       . /bootstrap.sh
       dockerize -wait tcp://postgres:5433 -timeout 15m -wait-retry-interval 10s 
       pyinstrument --outfile=/usr/src/${BACKEND_NAME}/profiling/outputs/profile_locations.html -m pytest -m locations profiling/test_locations.py::TestLocations
       pyinstrument --outfile=/usr/src/${BACKEND_NAME}/profiling/outputs/profile_targets.html -m pytest -m targets profiling/test_targets.py::TestTargets
       pyinstrument --outfile=/usr/src/${BACKEND_NAME}/profiling/outputs/profile_enumerators.html -m pytest -m enumerators profiling/test_enumerators.py::TestEnumerators
      
