version: '2'
services:
  api:
    image: ${STAGING_ACCOUNT}.dkr.ecr.ap-south-1.amazonaws.com/web-callisto-ecr-repository:backend
    cpu_shares: 400
    mem_limit: 300m
    restart: always
    ports:
      - "5001:5001"
    environment:
      - CONFIG_TYPE=config.StagingConfig
      - PYTHONUNBUFFERED=0
      - AWS_REGION=ap-south-1
      - ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
    command: api
    logging:
      driver: awslogs
      options:
        awslogs-group: dod_surveystream_webapp_callisto
        awslogs-region: ap-south-1
        awslogs-stream-prefix: dod_surveystream_backend
