"""
Targets : Add is_active column to targets table

Revision ID: 068d2207d058
Revises: 7338dc7732d2
Create Date: 2025-11-20 11:51:25.414591

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "068d2207d058"
down_revision = "7338dc7732d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("targets", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("targets", schema="webapp") as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
