"""

Add filters to email schedules

Revision ID: 0a33ae0946b4
Revises: b26f412cf185
Create Date: 2024-07-19 11:26:03.922107

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a33ae0946b4"
down_revision = "b26f412cf185"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_schedule_filters",
        sa.Column("email_schedule_uid", sa.Integer(), nullable=False),
        sa.Column("filter_group_id", sa.Integer(), nullable=False),
        sa.Column("filter_variable", sa.String(length=255), nullable=False),
        sa.Column("filter_operator", sa.String(length=16), nullable=False),
        sa.Column("filter_value", sa.Text(), nullable=False),
        sa.Column("filter_concatenator", sa.String(length=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_schedule_uid"],
            ["webapp.email_schedules.email_schedule_uid"],
            name=op.f("fk_email_schedule_filters_email_schedule_uid_email_schedules"),
        ),
        sa.PrimaryKeyConstraint(
            "email_schedule_uid",
            "filter_group_id",
            "filter_variable",
            "filter_operator",
            "filter_value",
            name=op.f("pk_email_schedule_filters"),
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_schedule_filters", schema="webapp")
    # ### end Alembic commands ###
