"""Add User locations table and columns for gender and languages in users table

Revision ID: 0c692fe689aa
Revises: c6731eec7e32
Create Date: 2024-07-30 03:55:13.136280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c692fe689aa'
down_revision = 'c6731eec7e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_user_mapping',
    sa.Column('survey_uid', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.Column('location_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_uid'], ['webapp.locations.location_uid'], name=op.f('fk_location_user_mapping_location_uid_locations')),
    sa.ForeignKeyConstraint(['survey_uid'], ['webapp.surveys.survey_uid'], name=op.f('fk_location_user_mapping_survey_uid_surveys')),
    sa.ForeignKeyConstraint(['user_uid'], ['webapp.users.user_uid'], name=op.f('fk_location_user_mapping_user_uid_users')),
    sa.PrimaryKeyConstraint('survey_uid', 'user_uid', 'location_uid', name=op.f('pk_location_user_mapping')),
    schema='webapp'
    )
    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.drop_column('languages')
        batch_op.drop_column('gender')

    op.drop_table('location_user_mapping', schema='webapp')
    # ### end Alembic commands ###
