"""Add media files config table

Revision ID: 0e0c398beec2
Revises: 5c87f42c12eb
Create Date: 2024-05-27 15:34:26.702509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0c398beec2'
down_revision = '5c87f42c12eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files_config',
    sa.Column('media_files_config_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_uid', sa.Integer(), nullable=False),
    sa.Column(
        'file_type',
        sa.String(), 
        sa.CheckConstraint(
            "file_type IN ('audio', 'photo')",
            name="ck_media_files_config_file_type",
        ),
        nullable=False
    ),
    sa.Column(
        'source', 
        sa.String(), 
        sa.CheckConstraint(
            "source IN ('SurveyCTO', 'Exotel')",
            name="ck_media_files_config_source",
        ),
        server_default='SurveyCTO', 
        nullable=False
    ),
    sa.Column('scto_fields', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['form_uid'], ['webapp.forms.form_uid'], name=op.f('fk_media_files_config_form_uid_forms')),
    sa.PrimaryKeyConstraint('media_files_config_uid', name=op.f('pk_media_files_config')),
    schema='webapp'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_files_config', schema='webapp')
    # ### end Alembic commands ###
