"""empty message

Revision ID: 0fea39569f9e
Revises: 0e0c398beec2
Create Date: 2024-06-05 05:02:56.609549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fea39569f9e'
down_revision = '0e0c398beec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_schedules', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('email_schedule_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_schedules', schema='webapp') as batch_op:
        batch_op.drop_column('email_schedule_name')

    # ### end Alembic commands ###
