"""Add assignments_table_config table

Revision ID: 11218c38d8e7
Revises: 683e16cb0795
Create Date: 2024-01-24 01:45:47.489312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11218c38d8e7"
down_revision = "683e16cb0795"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments_table_config",
        sa.Column("form_uid", sa.Integer(), nullable=False),
        sa.Column(
            "table_name",
            sa.String(),
            sa.CheckConstraint(
                "table_name IN ('assignments_main','assignments_surveyors','assignments_review', 'surveyors', 'targets')",
                name="ck_assignments_table_config_table_name",
            ),
            nullable=False,
        ),
        sa.Column("group_label", sa.String(), nullable=True),
        sa.Column("column_label", sa.String(), nullable=False),
        sa.Column("column_key", sa.String(), nullable=False),
        sa.Column("column_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_uid"],
            ["webapp.parent_forms.form_uid"],
            name=op.f("fk_assignments_table_config_form_uid_parent_forms"),
        ),
        sa.PrimaryKeyConstraint(
            "form_uid",
            "table_name",
            "column_key",
            name=op.f("pk_assignments_table_config"),
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assignments_table_config", schema="webapp")
    # ### end Alembic commands ###
