"""
Change filter_value column to be nullable.

Revision ID: 12975f0cd283
Revises: 19df8836b103
Create Date: 2024-09-04 09:33:55.155948

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "12975f0cd283"
down_revision = "19df8836b103"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###
