"""Adding unique contraint on media files config table

Revision ID: 17605263ee63
Revises: 46ba6d963fde
Create Date: 2024-06-13 08:09:14.417510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17605263ee63'
down_revision = '46ba6d963fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files_config', schema='webapp') as batch_op:
        batch_op.create_unique_constraint('_media_files_config_form_uid_file_type_source_uc', ['form_uid', 'file_type', 'source'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files_config', schema='webapp') as batch_op:
        batch_op.drop_constraint('_media_files_config_form_uid_file_type_source_uc', type_='unique')

    # ### end Alembic commands ###
