"""Adding 'other' to admin_form_type enum

Revision ID: 19df8836b103
Revises: eac40b6a1247
Create Date: 2024-08-30 11:01:28.607331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19df8836b103'
down_revision = 'eac40b6a1247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema='webapp') as batch_op:
        # Add 'other' to admin_form_type enum
        batch_op.drop_constraint('ck_forms_admin_form_type', type_='check')
        batch_op.create_check_constraint(
            "ck_forms_admin_form_type",
            sa.text("admin_form_type IN ('bikelog', 'account_details', 'other')"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema='webapp') as batch_op:
        batch_op.drop_constraint('ck_forms_admin_form_type', type_='check')
        batch_op.create_check_constraint(
            "ck_forms_admin_form_type",
            sa.text("admin_form_type IN ('bikelog', 'account_details')"),
        )

    # ### end Alembic commands ###
