"""Adding admin_form_type to forms model, add 'admin' to form_type enum 
and make target_id nullable in scto_question_mapping

Revision ID: 1d1aed6b6f50
Revises: cd4aaf081e89
Create Date: 2024-08-28 04:48:05.844945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1aed6b6f50'
down_revision = 'cd4aaf081e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('admin_form_type', sa.String(), nullable=True))
        batch_op.create_check_constraint(
            "ck_forms_admin_form_type",
            sa.text("admin_form_type IN ('bikelog', 'account_details')"),
        )
        # Add 'admin' to form_type enum
        batch_op.drop_constraint('ck_forms_form_type', type_='check')
        batch_op.create_check_constraint(
            "ck_forms_form_type", sa.text("form_type IN ('parent', 'dq', 'admin')")
        )

    with op.batch_alter_table('scto_question_mapping', schema='webapp') as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_question_mapping', schema='webapp') as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('ck_forms_admin_form_type', type_='check')

        # Remove 'admin' from form_type enum
        batch_op.drop_constraint('ck_forms_form_type', type_='check')
        batch_op.create_check_constraint(
            "ck_forms_form_type", sa.text("form_type IN ('parent', 'dq')")
        )

    with op.batch_alter_table('forms', schema='webapp') as batch_op:
        batch_op.drop_column('admin_form_type')

    # ### end Alembic commands ###
