"""
Email Tables: Add cascade on foreign keys

Revision ID: 24b0ab4789b4
Revises: f58a0e498a96
Create Date: 2024-09-12 08:23:41.053116

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "24b0ab4789b4"
down_revision = "f58a0e498a96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_email_schedule_filters_email_schedule_uid_email_schedules",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_email_schedule_filters_email_schedule_uid_email_schedules"),
            "email_schedules",
            ["email_schedule_uid"],
            ["email_schedule_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("email_schedules", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_email_schedules_email_config_uid_email_configs", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_email_schedules_email_config_uid_email_configs"),
            "email_configs",
            ["email_config_uid"],
            ["email_config_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_email_table_filters_email_template_table_uid_email_t_2ce5",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_email_table_filters_email_template_table_uid_email_template_tables"
            ),
            "email_template_tables",
            ["email_template_table_uid"],
            ["email_template_table_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("email_template_tables", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_email_template_tables_email_template_uid_email_templates",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_email_template_tables_email_template_uid_email_templates"),
            "email_templates",
            ["email_template_uid"],
            ["email_template_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("email_template_variables", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_email_template_variables_email_template_uid_email_templates",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_email_template_variables_email_template_uid_email_templates"
            ),
            "email_templates",
            ["email_template_uid"],
            ["email_template_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("email_templates", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_email_templates_email_config_uid_email_configs", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_email_templates_email_config_uid_email_configs"),
            "email_configs",
            ["email_config_uid"],
            ["email_config_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("manual_email_triggers", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_manual_email_triggers_email_config_uid_email_configs",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_manual_email_triggers_email_config_uid_email_configs"),
            "email_configs",
            ["email_config_uid"],
            ["email_config_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manual_email_triggers", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_manual_email_triggers_email_config_uid_email_configs"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_manual_email_triggers_email_config_uid_email_configs",
            "email_configs",
            ["email_config_uid"],
            ["email_config_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("email_templates", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_email_templates_email_config_uid_email_configs"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_templates_email_config_uid_email_configs",
            "email_configs",
            ["email_config_uid"],
            ["email_config_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("email_template_variables", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_email_template_variables_email_template_uid_email_templates"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_template_variables_email_template_uid_email_templates",
            "email_templates",
            ["email_template_uid"],
            ["email_template_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("email_template_tables", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_email_template_tables_email_template_uid_email_templates"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_template_tables_email_template_uid_email_templates",
            "email_templates",
            ["email_template_uid"],
            ["email_template_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_email_table_filters_email_template_table_uid_email_template_tables"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_table_filters_email_template_table_uid_email_t_2ce5",
            "email_template_tables",
            ["email_template_table_uid"],
            ["email_template_table_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("email_schedules", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_email_schedules_email_config_uid_email_configs"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_schedules_email_config_uid_email_configs",
            "email_configs",
            ["email_config_uid"],
            ["email_config_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_email_schedule_filters_email_schedule_uid_email_schedules"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_schedule_filters_email_schedule_uid_email_schedules",
            "email_schedules",
            ["email_schedule_uid"],
            ["email_schedule_uid"],
            referent_schema="webapp",
        )

    # ### end Alembic commands ###
