"""Add JSONB scto_fields to TargetStatus model

Revision ID: 29144c3ed8f9
Revises: cf68d3dcd91e
Create Date: 2024-02-19 17:28:24.676288
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29144c3ed8f9'
down_revision = 'cf68d3dcd91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_status', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('scto_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_status', schema='webapp') as batch_op:
        batch_op.drop_column('scto_fields')

    # ### end Alembic commands ###
