"""
Targets Config: Add preview_mode and targets_last_uploaded columns

Revision ID: 2a83ff36236b
Revises: e2cd5f73ac59
Create Date: 2025-01-17 06:02:21.396115

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a83ff36236b"
down_revision = "e2cd5f73ac59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_config", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column("targets_last_uploaded", sa.TIMESTAMP(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "preview_mode", sa.Boolean(), server_default="false", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_config", schema="webapp") as batch_op:
        batch_op.drop_column("preview_mode")
        batch_op.drop_column("targets_last_uploaded")

    # ### end Alembic commands ###
