"""
Add email table catalog and email template variables tables

Revision ID: 2e47ec936111
Revises: 42bd1483031b
Create Date: 2024-06-28 05:31:25.825270

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2e47ec936111"
down_revision = "42bd1483031b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_table_catalog",
        sa.Column("survey_uid", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=255), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=False),
        sa.Column("column_type", sa.String(length=255), nullable=False),
        sa.Column("column_description", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["survey_uid"],
            ["webapp.surveys.survey_uid"],
            name=op.f("fk_email_table_catalog_survey_uid_surveys"),
        ),
        sa.PrimaryKeyConstraint(
            "survey_uid",
            "table_name",
            "column_name",
            name=op.f("pk_email_table_catalog"),
        ),
        schema="webapp",
    )
    op.create_table(
        "email_template_variables",
        sa.Column("email_template_uid", sa.Integer(), nullable=False),
        sa.Column("variable_name", sa.String(length=100), nullable=False),
        sa.Column(
            "variable_type",
            sa.String(length=8),
            sa.CheckConstraint(
                "variable_type IN ('string','table')",
                name="ck_email_template_variables_variable_type",
            ),
            nullable=False,
        ),
        sa.Column("source_table", sa.String(length=255), nullable=True),
        sa.Column("variable_expression", sa.String(length=255), nullable=True),
        sa.Column(
            "table_column_mapping",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["email_template_uid"],
            ["webapp.email_templates.email_template_uid"],
            name=op.f("fk_email_template_variables_email_template_uid_email_templates"),
        ),
        sa.PrimaryKeyConstraint(
            "email_template_uid",
            "variable_name",
            name=op.f("pk_email_template_variables"),
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_template_variables", schema="webapp")
    op.drop_table("email_table_catalog", schema="webapp")
    # ### end Alembic commands ###
