"""Add surveyor_stats table

Revision ID: 3393b5cc3f28
Revises: 29144c3ed8f9
Create Date: 2024-02-21 04:16:09.945376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3393b5cc3f28'
down_revision = '29144c3ed8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveyor_stats',
    sa.Column('enumerator_uid', sa.Integer(), nullable=False),
    sa.Column('form_uid', sa.Integer(), nullable=False),
    sa.Column('avg_num_submissions_per_day', sa.Integer(), nullable=True),
    sa.Column('avg_num_completed_per_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enumerator_uid'], ['webapp.enumerators.enumerator_uid'], name=op.f('fk_surveyor_stats_enumerator_uid_enumerators')),
    sa.ForeignKeyConstraint(['form_uid'], ['webapp.parent_forms.form_uid'], name=op.f('fk_surveyor_stats_form_uid_parent_forms')),
    sa.PrimaryKeyConstraint('form_uid', 'enumerator_uid', name=op.f('pk_surveyor_stats')),
    schema='webapp'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveyor_stats', schema='webapp')
    # ### end Alembic commands ###
