"""Drop unique constraint on scto_form_questions

Revision ID: 33b8ce72b8e9
Revises: d798277afc23
Create Date: 2023-08-25 15:26:14.163020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33b8ce72b8e9"
down_revision = "6bfb561e1c00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scto_form_questions", schema="webapp") as batch_op:
        batch_op.drop_constraint("uq_scto_form_questions_form_uid", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scto_form_questions", schema="webapp") as batch_op:
        batch_op.create_unique_constraint(
            "uq_scto_form_questions_form_uid",
            ["form_uid", "question_name", "question_type"],
        )

    # ### end Alembic commands ###
