"""empty message

Revision ID: 356285f0f5d5
Revises: ffd697df5ae0
Create Date: 2024-06-20 07:30:03.381127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356285f0f5d5'
down_revision = 'ffd697df5ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('email_source_gsheet_link', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('email_source_gsheet_tab', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('email_source_gsheet_header_row', sa.Integer(), nullable=True))
        batch_op.drop_column('email_source_gsheet_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('email_source_gsheet_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_column('email_source_gsheet_header_row')
        batch_op.drop_column('email_source_gsheet_tab')
        batch_op.drop_column('email_source_gsheet_link')

    # ### end Alembic commands ###
