"""
Add target_scto_filters table

Revision ID: 388c4a422807
Revises: 92e3720f48ba
Create Date: 2024-11-13 12:17:55.011825

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "388c4a422807"
down_revision = "92e3720f48ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_scto_filters",
        sa.Column("filter_uid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("form_uid", sa.Integer(), nullable=False),
        sa.Column("filter_group_id", sa.Integer(), nullable=False),
        sa.Column("variable_name", sa.String(), nullable=False),
        sa.Column("filter_operator", sa.String(), nullable=False),
        sa.Column("filter_value", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_uid"],
            ["webapp.forms.form_uid"],
            name=op.f("fk_target_scto_filters_form_uid_forms"),
        ),
        sa.PrimaryKeyConstraint(
            "filter_uid", "filter_group_id", name=op.f("pk_target_scto_filters")
        ),
        sa.CheckConstraint(
            "filter_operator IN ('Is','Is not','Contains','Does not contain','Is Empty','Is not empty', 'Greather than', 'Smaller than')",
            name="ck_target_scto_filters_filter_operator",
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("target_scto_filters", schema="webapp")
    # ### end Alembic commands ###
