"""
Add Email Templates
Add Email Schedules
Add Email Manual Triggers

Revision ID: 3abe998c1cb1
Revises: 623e00cfc0e3
Create Date: 2024-04-12 09:11:51.414144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abe998c1cb1'
down_revision = '623e00cfc0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('email_template_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('email_template_uid', name=op.f('pk_email_templates')),
    sa.UniqueConstraint('template_name', name=op.f('uq_email_templates_template_name')),
    schema='webapp'
    )
    op.create_table('email_schedules',
    sa.Column('email_schedule_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_uid', sa.Integer(), nullable=False),
    sa.Column('dates', sa.ARRAY(sa.Date()), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('template_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_uid'], ['webapp.forms.form_uid'], name=op.f('fk_email_schedules_form_uid_forms')),
    sa.PrimaryKeyConstraint('email_schedule_uid', name=op.f('pk_email_schedules')),
    schema='webapp'
    )
    op.create_table('manual_email_triggers',
    sa.Column('manual_email_trigger_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_uid', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('recipients', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('template_uid', sa.Integer(), nullable=True),
    sa.Column(
        "status",
        sa.Enum("queued", "sent", "failed", name="status_enum"),
        sa.CheckConstraint(
            "status IN ('queued', 'sent', 'failed')",
            name="check_status",
        ),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['form_uid'], ['webapp.forms.form_uid'], name=op.f('fk_manual_email_triggers_form_uid_forms')),
    sa.PrimaryKeyConstraint('manual_email_trigger_uid', name=op.f('pk_manual_email_triggers')),
    schema='webapp'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_email_triggers', schema='webapp')
    op.drop_table('email_schedules', schema='webapp')
    op.drop_table('email_templates', schema='webapp')
    # ### end Alembic commands ###
