"""Add drop_duplicates column to dq_config table

Revision ID: 3c1fddf69707
Revises: d4f5516ae358
Create Date: 2025-04-30 06:29:34.899434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1fddf69707'
down_revision = 'd4f5516ae358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_config', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('drop_duplicates', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_config', schema='webapp') as batch_op:
        batch_op.drop_column('drop_duplicates')

    # ### end Alembic commands ###
