"""Adding module_dependency table
Updating config_status column constraint to allow the value 'Live'

Revision ID: 3e80e9fc2452
Revises: fe0d3ba92079
Create Date: 2025-01-31 11:18:03.578714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e80e9fc2452'
down_revision = 'fe0d3ba92079'
branch_labels = None
depends_on = None


def upgrade():

    op.create_table('module_dependency',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('requires_module_id', sa.Integer(), nullable=False),
    sa.Column('required_if', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['webapp.modules.module_id'], name=op.f('fk_module_dependency_module_id_modules')),
    sa.ForeignKeyConstraint(['requires_module_id'], ['webapp.modules.module_id'], name=op.f('fk_module_dependency_requires_module_id_modules')),
    sa.PrimaryKeyConstraint('module_id', 'requires_module_id', name=op.f('pk_module_dependency')),
    schema='webapp'
    )
    
    with op.batch_alter_table('module_status', schema='webapp') as batch_op:
        # Add 'Live' to config_status options
        batch_op.drop_constraint('ck_module_status_config_status', type_='check')
        batch_op.create_check_constraint(
            "ck_module_status_config_status", sa.text("config_status IN ('Done','In Progress','Not Started', 'Error', 'Live')")
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_dependency', schema='webapp')
    # ### end Alembic commands ###

    with op.batch_alter_table('module_status', schema='webapp') as batch_op:
        # Remove 'Live' from config_status options
        batch_op.drop_constraint('ck_module_status_config_status', type_='check')
        batch_op.create_check_constraint(
            "ck_module_status_config_status", sa.text("config_status IN ('Done','In Progress','Not Started', 'Error')")
        )
