"""
Add survey admins table
Update can_create_survey on the user table
Remove is_survey_admin from the user table
Update language on enumerators to be required

Revision ID: 3ea95fb8eced
Revises: 11218c38d8e7
Create Date: 2024-02-07 15:16:45.230486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ea95fb8eced"
down_revision = "11218c38d8e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "survey_admins",
        sa.Column("survey_admin_uid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("survey_uid", sa.Integer(), nullable=True),
        sa.Column("user_uid", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["survey_uid"],
            ["webapp.surveys.survey_uid"],
            name=op.f("fk_survey_admins_survey_uid_surveys"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["webapp.users.user_uid"],
            name=op.f("fk_survey_admins_user_uid_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("survey_admin_uid", name=op.f("pk_survey_admins")),
        sa.UniqueConstraint(
            "survey_uid", "user_uid", deferrable="True", name="_survey_uid_user_uid_uc"
        ),
        schema="webapp",
    )
    with op.batch_alter_table("enumerators", schema="webapp") as batch_op:
        batch_op.alter_column("language", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("users", schema="webapp") as batch_op:
        batch_op.add_column(sa.Column("can_create_survey", sa.Boolean(), nullable=True))
        batch_op.drop_column("is_survey_admin")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_survey_admin", sa.BOOLEAN(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("can_create_survey")

    with op.batch_alter_table("enumerators", schema="webapp") as batch_op:
        batch_op.alter_column("language", existing_type=sa.VARCHAR(), nullable=True)

    op.drop_table("survey_admins", schema="webapp")
    # ### end Alembic commands ###
