"""
Email Delivery report- Set foreign key as ondelete CASCADE

Revision ID: 40ee53f5075b
Revises: 7ee6e8c4b2b0
Create Date: 2024-10-15 14:11:01.641388

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40ee53f5075b"
down_revision = "7ee6e8c4b2b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_delivery_reports", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_email_delivery_reports_email_schedule_uid_email_schedules",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_email_delivery_reports_manual_email_trigger_uid_manu_392d",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_email_delivery_reports_email_schedule_uid_email_schedules"),
            "email_schedules",
            ["email_schedule_uid"],
            ["email_schedule_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_email_delivery_reports_manual_email_trigger_uid_manual_email_triggers"
            ),
            "manual_email_triggers",
            ["manual_email_trigger_uid"],
            ["manual_email_trigger_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table(
        "email_enumerator_delivery_status", schema="webapp"
    ) as batch_op:
        batch_op.drop_constraint(
            "fk_email_enumerator_delivery_status_enumerator_uid_enumerators",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_email_enumerator_delivery_status_enumerator_uid_enumerators"
            ),
            "enumerators",
            ["enumerator_uid"],
            ["enumerator_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "email_enumerator_delivery_status", schema="webapp"
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_email_enumerator_delivery_status_enumerator_uid_enumerators"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_enumerator_delivery_status_enumerator_uid_enumerators",
            "enumerators",
            ["enumerator_uid"],
            ["enumerator_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("email_delivery_reports", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_email_delivery_reports_manual_email_trigger_uid_manual_email_triggers"
            ),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_email_delivery_reports_email_schedule_uid_email_schedules"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_email_delivery_reports_manual_email_trigger_uid_manu_392d",
            "manual_email_triggers",
            ["manual_email_trigger_uid"],
            ["manual_email_trigger_uid"],
            referent_schema="webapp",
        )
        batch_op.create_foreign_key(
            "fk_email_delivery_reports_email_schedule_uid_email_schedules",
            "email_schedules",
            ["email_schedule_uid"],
            ["email_schedule_uid"],
            referent_schema="webapp",
        )

    # ### end Alembic commands ###
