"""Add target_mapping_criteria column and rename supervisor_assignment_criteria to surveyor_mapping_criteria

Revision ID: 41df9d253183
Revises: b26f412cf185
Create Date: 2024-07-23 08:01:22.529701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41df9d253183'
down_revision = 'b26f412cf185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_questionnaire', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('target_mapping_criteria', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.alter_column('supervisor_assignment_criteria', nullable=True, new_column_name='surveyor_mapping_criteria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_questionnaire', schema='webapp') as batch_op:
        batch_op.alter_column('surveyor_mapping_criteria', nullable=True, new_column_name='supervisor_assignment_criteria')
        batch_op.drop_column('target_mapping_criteria')

    # ### end Alembic commands ###
