"""Add column for DQ enumerator ID in scto_question_mapping

Revision ID: 42bd1483031b
Revises: 356285f0f5d5
Create Date: 2024-06-27 07:03:02.907021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bd1483031b'
down_revision = '356285f0f5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_question_mapping', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('dq_enumerator_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_question_mapping', schema='webapp') as batch_op:
        batch_op.drop_column('dq_enumerator_id')

    # ### end Alembic commands ###
