"""Add surveyor assignments table

Revision ID: 477d50f4a869
Revises: 8eec90719523
Create Date: 2024-01-09 02:01:42.025410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "477d50f4a869"
down_revision = "8eec90719523"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surveyor_assignments",
        sa.Column("target_uid", sa.Integer(), nullable=False),
        sa.Column("enumerator_uid", sa.Integer(), nullable=False),
        sa.Column("user_uid", sa.Integer(), nullable=True),
        sa.Column("to_delete", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enumerator_uid"],
            ["webapp.enumerators.enumerator_uid"],
            name=op.f("fk_surveyor_assignments_enumerator_uid_enumerators"),
        ),
        sa.ForeignKeyConstraint(
            ["target_uid"],
            ["webapp.targets.target_uid"],
            name=op.f("fk_surveyor_assignments_target_uid_targets"),
        ),
        sa.PrimaryKeyConstraint("target_uid", name=op.f("pk_surveyor_assignments")),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("surveyor_assignments")
    # ### end Alembic commands ###
