"""Adding columns for storing google sheet information for media files

Revision ID: 48b3877a09e6
Revises: 40ee53f5075b
Create Date: 2024-10-18 07:51:29.440355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b3877a09e6'
down_revision = '5d4b3e62712d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files_config', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('google_sheet_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mapping_google_sheet_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files_config', schema='webapp') as batch_op:
        batch_op.drop_column('mapping_google_sheet_key')
        batch_op.drop_column('google_sheet_key')

    # ### end Alembic commands ###
