"""Add module_id column to permissions

Revision ID: 4ba0f2701c55
Revises: 7fde6781c647
Create Date: 2024-09-06 05:04:47.513496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba0f2701c55'
down_revision = '7fde6781c647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_permissions_module_id_modules'), 'modules', ['module_id'], ['module_id'], referent_schema='webapp', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema='webapp') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_permissions_module_id_modules'), type_='foreignkey')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
