"""Adding group_by_module_name column to dq_config

Revision ID: 4e9aef7ac61d
Revises: 388c4a422807
Create Date: 2024-12-06 12:00:27.738654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9aef7ac61d'
down_revision = '9de0bf390ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_config', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('group_by_module_name', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_config', schema='webapp') as batch_op:
        batch_op.drop_column('group_by_module_name')

    # ### end Alembic commands ###
