"""empty message

Revision ID: 53ad7e78b4d4
Revises: 356285f0f5d5
Create Date: 2024-06-21 17:34:18.366985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53ad7e78b4d4'
down_revision = '356285f0f5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template_variables',
    sa.Column('email_template_uid', sa.Integer(), nullable=False),
    sa.Column('variable_name', sa.String(length=100), nullable=False),
    sa.Column('variable_type', sa.String(length=32), nullable=False),
    sa.Column('source_table', sa.String(length=255), nullable=True),
    sa.Column('variable_expression', sa.String(length=255), nullable=True),
    sa.Column('table_column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['email_template_uid'], ['webapp.email_templates.email_template_uid'], name=op.f('fk_email_template_variables_email_template_uid_email_templates')),
    sa.PrimaryKeyConstraint('email_template_uid', 'variable_name', name=op.f('pk_email_template_variables')),
    schema='webapp'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_template_variables', schema='webapp')
    # ### end Alembic commands ###
