"""Adding dq_config, dq_checks, dq_check_types, dq_check_filters tables for data quality checks configuration

Revision ID: 55b9ef040163
Revises: 48b3877a09e6
Create Date: 2024-10-24 04:39:55.187973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b9ef040163'
down_revision = '9f4edc77675a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dq_check_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('type_id', name=op.f('pk_dq_check_types')),
    schema='webapp'
    )
    
    op.create_table('dq_checks',
    sa.Column('dq_check_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_uid', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('all_questions', sa.Boolean(), nullable=False),
    sa.Column('question_name', sa.String(), nullable=True),
    sa.Column('dq_scto_form_uid', sa.Integer(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=True),
    sa.Column('flag_description', sa.String(), nullable=True),
    sa.Column('check_components', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dq_scto_form_uid'], ['webapp.forms.form_uid'], name=op.f('fk_dq_checks_dq_scto_form_uid_forms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_uid'], ['webapp.forms.form_uid'], name=op.f('fk_dq_checks_form_uid_forms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['webapp.dq_check_types.type_id'], name=op.f('fk_dq_checks_type_id_dq_check_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dq_check_uid', name=op.f('pk_dq_checks')),
    schema='webapp'
    )

    op.create_table('dq_config',
    sa.Column('form_uid', sa.Integer(), nullable=False),
    sa.Column('survey_status_filter', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['form_uid'], ['webapp.forms.form_uid'], name=op.f('fk_dq_config_form_uid_forms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_uid', name=op.f('pk_dq_config')),
    schema='webapp'
    )

    op.create_table('dq_check_filters',
    sa.Column('filter_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dq_check_uid', sa.Integer(), nullable=False),
    sa.Column('filter_group_id', sa.Integer(), nullable=False),
    sa.Column('question_name', sa.String(), nullable=False),
    sa.Column(
        'filter_operator', 
        sa.String(), 
        sa.CheckConstraint(
            """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is Empty',
                'Is not empty',
                'Greather than',
                'Smaller than')""",
            name="ck_dq_check_filters_filter_operator",
        ),
        nullable=False),
    sa.Column('filter_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dq_check_uid'], ['webapp.dq_checks.dq_check_uid'], name=op.f('fk_dq_check_filters_dq_check_uid_dq_checks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filter_uid', 'dq_check_uid', 'filter_group_id', name=op.f('pk_dq_check_filters')),
    schema='webapp'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dq_check_filters', schema='webapp')
    op.drop_table('dq_config', schema='webapp')
    op.drop_table('dq_checks', schema='webapp')
    op.drop_table('dq_check_types', schema='webapp')
    # ### end Alembic commands ###
