"""
Add Email Configs
Add Email Templates
Add Email Schedules
Add Email Manual Triggers

Revision ID: 5c87f42c12eb
Revises: 623e00cfc0e3
Create Date: 2024-04-20 12:16:36.546525

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c87f42c12eb"
down_revision = "623e00cfc0e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_configs",
        sa.Column("email_config_uid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("config_type", sa.String(length=100), nullable=False),
        sa.Column("form_uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_uid"],
            ["webapp.forms.form_uid"],
            name=op.f("fk_email_configs_form_uid_forms"),
        ),
        sa.PrimaryKeyConstraint("email_config_uid", name=op.f("pk_email_configs")),
        sa.UniqueConstraint(
            "config_type", "form_uid", name="_email_configs_config_type_form_uid_uc"
        ),
        schema="webapp",
    )
    op.create_table(
        "email_schedules",
        sa.Column(
            "email_schedule_uid", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("email_config_uid", sa.Integer(), nullable=False),
        sa.Column("dates", sa.ARRAY(sa.Date()), nullable=False),
        sa.Column("time", sa.TIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_config_uid"],
            ["webapp.email_configs.email_config_uid"],
            name=op.f("fk_email_schedules_email_config_uid_email_configs"),
        ),
        sa.PrimaryKeyConstraint("email_schedule_uid", name=op.f("pk_email_schedules")),
        schema="webapp",
    )
    op.create_table(
        "email_templates",
        sa.Column(
            "email_template_uid", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("email_config_uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_config_uid"],
            ["webapp.email_configs.email_config_uid"],
            name=op.f("fk_email_templates_email_config_uid_email_configs"),
        ),
        sa.PrimaryKeyConstraint("email_template_uid", name=op.f("pk_email_templates")),
        schema="webapp",
    )
    op.create_table(
        "manual_email_triggers",
        sa.Column(
            "manual_email_trigger_uid", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("email_config_uid", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.TIME(), nullable=False),
        sa.Column("recipients", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column(
            "status",
            sa.String(length=100),
            sa.CheckConstraint(
                "status IN ('queued', 'sent', 'failed', 'progress', 'running')",
                name="check_status",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_config_uid"],
            ["webapp.email_configs.email_config_uid"],
            name=op.f("fk_manual_email_triggers_email_config_uid_email_configs"),
        ),
        sa.PrimaryKeyConstraint(
            "manual_email_trigger_uid", name=op.f("pk_manual_email_triggers")
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manual_email_triggers", schema="webapp")
    op.drop_table("email_templates", schema="webapp")
    op.drop_table("email_schedules", schema="webapp")
    op.drop_table("email_configs", schema="webapp")
    # ### end Alembic commands ###
