"""
Update the check constraint for filter_operator in email_schedule_filters and email_table_filters tables

Revision ID: 5d4b3e62712d
Revises: 40ee53f5075b
Create Date: 2024-10-21 08:03:53.989727

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d4b3e62712d"
down_revision = "40ee53f5075b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint("ck_email_schedule_filter_operator", type_="check")
        batch_op.add_constraint(
            sa.CheckConstraint(
                """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is empty',
                'Is not empty',
                'Greater than',
                'Smaller than',
                'Date: Is Current Date',
                'Date: In last week',
                'Date: In last month',
                'Date: In Date Range'
            )""",
                name="ck_email_schedule_filter_operator",
            )
        )

    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint("ck_email_table_filter_operator", type_="check")
        batch_op.add_constraint(
            sa.CheckConstraint(
                """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is empty',
                'Is not empty',
                'Greater than',
                'Smaller than',
                'Date: Is Current Date',
                'Date: In last week',
                'Date: In last month',
                'Date: In Date Range'
            )""",
                name="ck_email_table_filter_operator",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint("ck_email_schedule_filter_operator", type_="check")

    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.drop_constraint("ck_email_table_filter_operator", type_="check")

    # ### end Alembic commands ###
