"""empty message

Revision ID: 6204e026bf7a
Revises: b26f412cf185
Create Date: 2024-07-25 09:45:16.150413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6204e026bf7a'
down_revision = 'b26f412cf185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_schedule_filters',
    sa.Column('email_schedule_uid', sa.Integer(), nullable=False),
    sa.Column('filter_group_id', sa.Integer(), nullable=False),
    sa.Column('filter_variable', sa.String(length=255), nullable=False),
    sa.Column('filter_operator', sa.String(length=16), nullable=False),
    sa.Column('filter_value', sa.Text(), nullable=False),
    sa.Column('filter_concatenator', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['email_schedule_uid'], ['webapp.email_schedules.email_schedule_uid'], name=op.f('fk_email_schedule_filters_email_schedule_uid_email_schedules')),
    sa.PrimaryKeyConstraint('email_schedule_uid', 'filter_group_id', 'filter_variable', 'filter_operator', 'filter_value', name=op.f('pk_email_schedule_filters')),
    schema='webapp'
    )
    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('config_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('_email_configs_config_type_form_uid_uc', type_='unique')
        batch_op.create_unique_constraint('_email_configs_config_name_form_uid_uc', ['config_name', 'form_uid'])
        batch_op.drop_column('config_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('config_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint('_email_configs_config_name_form_uid_uc', type_='unique')
        batch_op.create_unique_constraint('_email_configs_config_type_form_uid_uc', ['config_type', 'form_uid'])
        batch_op.drop_column('config_name')

    op.drop_table('email_schedule_filters', schema='webapp')
    # ### end Alembic commands ###
