"""Add drop_duplicates column to dq_config table

Revision ID: 631e9daa33d0
Revises: d4f5516ae358
Create Date: 2025-05-07 08:48:39.227123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631e9daa33d0'
down_revision = 'd4f5516ae358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_config', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('drop_duplicates', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_config', schema='webapp') as batch_op:
        batch_op.drop_column('drop_duplicates')

    # ### end Alembic commands ###
