"""
Add notification actions, templates and mappings

Revision ID: 6508381ec406
Revises: e2cd5f73ac59
Create Date: 2025-01-14 07:44:08.816681

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6508381ec406"
down_revision = "e2cd5f73ac59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_actions",
        sa.Column(
            "notification_action_uid", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["webapp.modules.module_id"],
            name=op.f("fk_notification_actions_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_action_uid", name=op.f("pk_notification_actions")
        ),
        sa.UniqueConstraint("module_id", "name", name="uc_notification_actions"),
        schema="webapp",
    )
    op.create_table(
        "notification_templates",
        sa.Column(
            "notification_template_uid",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.String(length=8),
            sa.CheckConstraint(
                "severity IN ('alert','warning','error')",
                name="ck_notification_templates_severity",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["webapp.modules.module_id"],
            name=op.f("fk_notification_templates_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_template_uid", name=op.f("pk_notification_templates")
        ),
        sa.UniqueConstraint("module_id", "name", name="uc_notification_templates"),
        schema="webapp",
    )
    op.create_table(
        "notification_action_mappings",
        sa.Column(
            "notification_condition_uid",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("notification_action_uid", sa.Integer(), nullable=False),
        sa.Column("notification_template_uid", sa.Integer(), nullable=False),
        sa.Column("condition", sa.ARRAY(sa.String(length=128)), nullable=True),
        sa.ForeignKeyConstraint(
            ["notification_action_uid"],
            ["webapp.notification_actions.notification_action_uid"],
            name=op.f(
                "fk_notification_action_mappings_notification_action_uid_notification_actions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["notification_template_uid"],
            ["webapp.notification_templates.notification_template_uid"],
            name=op.f(
                "fk_notification_action_mappings_notification_template_uid_notification_templates"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_condition_uid", name=op.f("pk_notification_action_mappings")
        ),
        sa.UniqueConstraint(
            "notification_action_uid",
            "notification_template_uid",
            name="uc_notification_action_mappings",
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_action_mappings", schema="webapp")
    op.drop_table("notification_templates", schema="webapp")
    op.drop_table("notification_actions", schema="webapp")
    # ### end Alembic commands ###
