"""
Update surveys table
- add created_by_user_id : used to identify specific survey_admin surveys

Update users table
- add is_survey_admin : used to identify if user is allowed to create new surveys

Revision ID: 683e16cb0795
Revises: 477d50f4a869
Create Date: 2024-01-23 07:06:00.564978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683e16cb0795'
down_revision = '477d50f4a869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('created_by_user_uid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_surveys_created_by_user_uid_users'), 'users', ['created_by_user_uid'], ['user_uid'], referent_schema='webapp')

    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('is_survey_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.drop_column('is_survey_admin')

    with op.batch_alter_table('surveys', schema='webapp') as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_surveys_created_by_user_uid_users'), type_='foreignkey')
        batch_op.drop_column('created_by_user_uid')

    # ### end Alembic commands ###
