"""Remove created_by_user_uid from surveys

Revision ID: 6bfb561e1c00
Revises: d798277afc23
Create Date: 2023-08-24 19:07:14.938826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bfb561e1c00"
down_revision = "d798277afc23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("surveys", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_surveys_created_by_user_uid_users", type_="foreignkey"
        )
        batch_op.drop_column("created_by_user_uid")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("surveys", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_by_user_uid", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.create_foreign_key(
            "fk_surveys_created_by_user_uid_users",
            "users",
            ["created_by_user_uid"],
            ["user_uid"],
            referent_schema="webapp",
        )

    # ### end Alembic commands ###
