"""
Add notification tables

Revision ID: 6c8f1f037fa4
Revises: 388c4a422807
Create Date: 2024-11-29 12:30:24.648627

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c8f1f037fa4"
down_revision = "388c4a422807"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notifications",
        sa.Column(
            "user_notification_uid", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_uid", sa.Integer(), nullable=True),
        sa.Column(
            "notification_type",
            sa.String(length=8),
            sa.CheckConstraint(
                "notification_type IN ('alert','warning','error')",
                name="ck_survey_notifications_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "notification_status",
            sa.String(length=16),
            sa.CheckConstraint(
                "notification_status IN ('in progress','done')",
                name="ck_survey_notifications_status",
            ),
            nullable=False,
        ),
        sa.Column("notification_message", sa.Text(), nullable=False),
        sa.Column(
            "notification_timestamp",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["webapp.users.user_uid"],
            name=op.f("fk_user_notifications_user_uid_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_notification_uid", name=op.f("pk_user_notifications")
        ),
        schema="webapp",
    )
    op.create_table(
        "survey_notifications",
        sa.Column("notification_uid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("survey_uid", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            sa.String(length=8),
            sa.CheckConstraint(
                "notification_type IN ('alert','warning','error')",
                name="ck_user_notifications_type",
            ),
            server_default="alert",
            nullable=False,
        ),
        sa.Column(
            "notification_status",
            sa.String(length=16),
            sa.CheckConstraint(
                "notification_status IN ('in progress','done')",
                name="ck_user_notifications_status",
            ),
            server_default="in progress",
            nullable=False,
        ),
        sa.Column("notification_message", sa.Text(), nullable=False),
        sa.Column(
            "notification_timestamp",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["webapp.modules.module_id"],
            name=op.f("fk_survey_notifications_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["survey_uid"],
            ["webapp.surveys.survey_uid"],
            name=op.f("fk_survey_notifications_survey_uid_surveys"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_uid", name=op.f("pk_survey_notifications")
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("survey_notifications", schema="webapp")
    op.drop_table("user_notifications", schema="webapp")
    # ### end Alembic commands ###
