"""Remove to_delete column for users

Revision ID: 702360394ae3
Revises: 3393b5cc3f28
Create Date: 2024-04-02 06:25:37.929693

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "702360394ae3"
down_revision = "3393b5cc3f28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema="webapp") as batch_op:
        batch_op.drop_column("to_delete")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column("to_delete", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
