"""Removing primary key constraint on choice labels table and adding choice_label_uid as primary key.
This migration is necessary to handle the fact that SurveyCTO does not enforce uniqueness on (list_uid, choice_value, language)
and allows duplicate entries. The new choice_label_uid will serve as the primary key for the table.

Revision ID: 7338dc7732d2
Revises: 9381e3a4dabc
Create Date: 2025-08-22 19:15:31.437099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7338dc7732d2'
down_revision = '9381e3a4dabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_form_choice_labels', schema='webapp') as batch_op:
        batch_op.drop_constraint(
            'pk_scto_form_choice_labels', type_='primary',
            schema='webapp'
        )
        batch_op.add_column(sa.Column('choice_label_uid', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.create_primary_key(
            'pk_scto_form_choice_labels', ['choice_label_uid'], schema='webapp'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_form_choice_labels', schema='webapp') as batch_op:
        
        batch_op.drop_constraint(
            'pk_scto_form_choice_labels', type_='primary',
            schema='webapp'
        )
        batch_op.drop_column('choice_label_uid')
        batch_op.create_primary_key(
            'pk_scto_form_choice_labels', ['list_uid', 'choice_value', 'language'], schema='webapp'
        )

    # ### end Alembic commands ###
