"""
Add Target Config table

Revision ID: 7c9fc25d9651
Revises: 40ee53f5075b
Create Date: 2024-10-16 11:22:20.429391

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c9fc25d9651"
down_revision = "40ee53f5075b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_config",
        sa.Column("form_uid", sa.Integer(), nullable=False),
        sa.Column(
            "target_source",
            sa.String(length=8),
            sa.CheckConstraint(
                "target_source IN ('csv','scto')",
                name="ck_target_config_target_source",
            ),
            server_default="csv",
            nullable=False,
        ),
        sa.Column(
            "scto_input_type",
            sa.String(length=8),
            sa.CheckConstraint(
                "scto_input_type IN ('dataset','form')",
                name="ck_target_config_scto_input_type",
            ),
            nullable=True,
        ),
        sa.Column("scto_input_id", sa.String(length=256), nullable=True),
        sa.Column(
            "scto_encryption_flag", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["form_uid"],
            ["webapp.forms.form_uid"],
            name=op.f("fk_target_config_form_uid_forms"),
        ),
        sa.PrimaryKeyConstraint("form_uid", name=op.f("pk_target_config")),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("target_config", schema="webapp")
    # ### end Alembic commands ###
