"""
Email : Update Filter types with date filters

Revision ID: 7ee6e8c4b2b0
Revises: ce482510bdd1
Create Date: 2024-10-11 06:42:33.563763

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ee6e8c4b2b0"
down_revision = "ce482510bdd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.alter_column(
            "filter_operator",
            existing_type=sa.VARCHAR(length=16),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.drop_constraint("ck_email_schedule_filter_operator", type_="check")
        batch_op.create_check_constraint(
            "ck_email_schedule_filter_operator",
            """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is Empty',
                'Is not empty',
                'Greather than',
                'Smaller than',
                'Date: Is Current Date',
                'Date: In last week',
                'Date: In last month',
                'Date: In Date Range')""",
        )

    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.alter_column(
            "filter_operator",
            existing_type=sa.VARCHAR(length=16),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.drop_constraint("ck_email_table_filter_operator", type_="check")
        batch_op.create_check_constraint(
            "ck_email_table_filter_operator",
            """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is Empty',
                'Is not empty',
                'Greather than',
                'Smaller than',
                'Date: Is Current Date',
                'Date: In last week',
                'Date: In last month',
                'Date: In Date Range')""",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.alter_column(
            "filter_operator",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
        )

    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.alter_column(
            "filter_operator",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
