"""
Modify Filters table, set filter value as nullable and remove filter_concatenator column

Revision ID: 7fde6781c647
Revises: 19df8836b103
Create Date: 2024-09-04 10:29:12.877749

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7fde6781c647"
down_revision = "19df8836b103"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "schedule_filter_uid", sa.Integer(), autoincrement=True, nullable=False
            )
        )
        batch_op.alter_column(
            "filter_group_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=True)
        batch_op.drop_column("filter_concatenator")

    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "table_filter_uid", sa.Integer(), autoincrement=True, nullable=False
            )
        )
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=True)
        batch_op.drop_column("filter_concatenator")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_table_filters", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "filter_concatenator",
                sa.VARCHAR(length=4),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("table_filter_uid")

    with op.batch_alter_table("email_schedule_filters", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "filter_concatenator",
                sa.VARCHAR(length=4),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.alter_column("filter_value", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "filter_group_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("schedule_filter_uid")

    # ### end Alembic commands ###
