"""Remove default value form form_type column

Revision ID: 83fdb210735b
Revises: a79f288443a5
Create Date: 2024-04-07 20:00:33.794966

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83fdb210735b"
down_revision = "a79f288443a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forms", schema="webapp") as batch_op:
        batch_op.alter_column(
            "form_type",
            existing_type=sa.VARCHAR(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forms", schema="webapp") as batch_op:
        batch_op.alter_column(
            "form_type",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("'parent'::character varying"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
