"""
Add Email Schedules
Add Email Templates
Add Manual Email Triggers

Revision ID: 842a7b01e71c
Revises: 83fdb210735b
Create Date: 2024-04-08 07:50:49.683164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842a7b01e71c'
down_revision = '83fdb210735b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_schedules',
    sa.Column('email_schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.ARRAY(sa.Date()), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('template_uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('email_schedule_id', name=op.f('pk_email_schedules'))
    )
    op.create_table('email_templates',
    sa.Column('email_template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('email_template_id', name=op.f('pk_email_templates')),
    sa.UniqueConstraint('template_name', name=op.f('uq_email_templates_template_name'))
    )
    op.create_table('manual_email_triggers',
    sa.Column('manual_email_trigger_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('recipients', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('template_uid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('manual_email_trigger_id', name=op.f('pk_manual_email_triggers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_email_triggers')
    op.drop_table('email_templates')
    op.drop_table('email_schedules')
    # ### end Alembic commands ###
