"""empty message

Revision ID: 864ad0b428d8
Revises: fe0d3ba92079
Create Date: 2025-01-24 10:59:27.509502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864ad0b428d8'
down_revision = 'fe0d3ba92079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('number_of_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema='webapp') as batch_op:
        batch_op.drop_column('number_of_attempts')

    # ### end Alembic commands ###
