"""
Add number_of_attempts column to forms table

Revision ID: 8b17cd15773c
Revises: bf0794f8d800
Create Date: 2025-03-12 05:16:09.923712

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b17cd15773c"
down_revision = "bf0794f8d800"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forms", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column("number_of_attempts", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forms", schema="webapp") as batch_op:
        batch_op.drop_column("number_of_attempts")

    # ### end Alembic commands ###
