"""empty message

Revision ID: 8b47bebabbf2
Revises: 5c87f42c12eb
Create Date: 2024-05-28 16:01:56.781004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b47bebabbf2'
down_revision = '5c87f42c12eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_schedules', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('email_schedule_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_schedules', schema='webapp') as batch_op:
        batch_op.drop_column('email_schedule_name')

    # ### end Alembic commands ###
