"""
Update the users table to contain a to_delete column
This will be used to mark users as deleted

Revision ID: 8eec90719523
Revises: 4a1f22967088
Create Date: 2023-12-14 13:28:23.729217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eec90719523'
down_revision = '4a1f22967088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('to_delete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.drop_column('to_delete')

    # ### end Alembic commands ###
