"""Update Enumerators
- make language non nullable

Revision ID: 8f75c9ef843f
Revises: 11218c38d8e7
Create Date: 2024-01-31 10:50:28.171124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f75c9ef843f'
down_revision = '11218c38d8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enumerators', schema='webapp') as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enumerators', schema='webapp') as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
