"""
Target Column Config- Add column_source column to store input column name

Revision ID: 92e3720f48ba
Revises: 55b9ef040163
Create Date: 2024-11-05 15:46:51.016399

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92e3720f48ba"
down_revision = "55b9ef040163"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.add_column(sa.Column("column_source", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.drop_column("column_source")

    # ### end Alembic commands ###
