"""Add enumerator_column_config table

Revision ID: 92edc2e0b7a7
Revises: d4f099a62133
Create Date: 2023-08-12 18:35:38.684685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92edc2e0b7a7"
down_revision = "d4f099a62133"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enumerator_column_config",
        sa.Column("form_uid", sa.Integer(), nullable=False),
        sa.Column("column_name", sa.String(), nullable=False),
        sa.Column(
            "column_type",
            sa.String(),
            sa.CheckConstraint(
                "column_type IN ('personal_details','custom_fields','location')",
                name="ck_enumerator_column_config_column_type",
            ),
            nullable=False,
        ),
        sa.Column("bulk_editable", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_uid"],
            ["webapp.parent_forms.form_uid"],
            name=op.f("fk_enumerator_column_config_form_uid_parent_forms"),
        ),
        sa.PrimaryKeyConstraint(
            "form_uid", "column_name", name=op.f("pk_enumerator_column_config")
        ),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enumerator_column_config", schema="webapp")
    # ### end Alembic commands ###
