"""
Targets Column Config : Add allow_null_values column, remove bulk_editable column
Enumerators Column Config : Add allow_null_values column, remove bulk_editable column

Revision ID: 9381e3a4dabc
Revises: c5530d333545
Create Date: 2025-07-17 09:46:19.654472

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9381e3a4dabc"
down_revision = "c5530d333545"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("enumerator_column_config", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "allow_null_values", sa.Boolean(), server_default="true", nullable=False
            )
        )
        batch_op.drop_column("bulk_editable")

    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "allow_null_values", sa.Boolean(), server_default="true", nullable=False
            )
        )
        batch_op.drop_column("bulk_editable")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "bulk_editable", sa.BOOLEAN(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("allow_null_values")

    with op.batch_alter_table("enumerator_column_config", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column(
                "bulk_editable", sa.BOOLEAN(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("allow_null_values")

    # ### end Alembic commands ###
