"""

Add notification action and template tables

Revision ID: a09632ea91ad
Revises: dbb88ef67228
Create Date: 2024-12-20 08:11:37.398495

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a09632ea91ad"
down_revision = "dbb88ef67228"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_actions",
        sa.Column(
            "notification_action_uid", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_template_list", sa.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["webapp.modules.module_id"],
            name=op.f("fk_notification_actions_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_action_uid", name=op.f("pk_notification_actions")
        ),
        sa.UniqueConstraint("module_id", "name", name="uc_notification_actions"),
        schema="webapp",
    )
    op.create_table(
        "notification_templates",
        sa.Column(
            "notification_template_uid",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.String(length=8),
            sa.CheckConstraint(
                "severity IN ('alert','warning','error')",
                name="ck_notification_templates_severity",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["webapp.modules.module_id"],
            name=op.f("fk_notification_templates_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "notification_template_uid", name=op.f("pk_notification_templates")
        ),
        sa.UniqueConstraint("module_id", "name", name="uc_notification_templates"),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_templates", schema="webapp")
    op.drop_table("notification_actions", schema="webapp")
    # ### end Alembic commands ###
