"""Modify forms table to store both parent and dq forms

Revision ID: a79f288443a5
Revises: 702360394ae3
Create Date: 2024-04-04 18:42:06.420757

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a79f288443a5"
down_revision = "702360394ae3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Start by dropping the foreign key constraints that reference the parent_forms.form_uid primary key

    with op.batch_alter_table("assignments_table_config", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_assignments_table_config_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("enumerator_column_config", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_enumerator_column_config_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("enumerators", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_enumerators_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("location_monitor_mapping", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_location_monitor_mapping_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("location_surveyor_mapping", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_location_surveyor_mapping_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("monitor_forms", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_monitor_forms_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("scto_form_choice_lists", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_scto_form_choice_lists_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("scto_form_questions", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_scto_form_questions_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("scto_form_settings", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_scto_form_settings_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("scto_question_mapping", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_scto_question_mapping_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("surveyor_forms", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_surveyor_forms_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("surveyor_stats", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_surveyor_stats_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "fk_target_column_config_form_uid_parent_forms", type_="foreignkey"
        )

    with op.batch_alter_table("targets", schema="webapp") as batch_op:
        batch_op.drop_constraint("fk_targets_form_uid_parent_forms", type_="foreignkey")

    # Rename the parent_forms table to forms, add the new columns, and update the constraints
    op.rename_table("parent_forms", "forms", schema="webapp")
    with op.batch_alter_table("forms", schema="webapp") as batch_op:
        batch_op.add_column(sa.Column("form_type", sa.String(), nullable=False))
        batch_op.create_check_constraint(
            "ck_forms_form_type", sa.text("form_type IN ('parent', 'dq')")
        )
        batch_op.add_column(sa.Column("dq_form_type", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("parent_form_uid", sa.Integer(), nullable=True))

        batch_op.drop_constraint("pk_parent_forms", type_="primary")
        batch_op.create_primary_key("pk_forms", ["form_uid"])

        # Rename the primary key sequence
        batch_op.execute(
            "ALTER SEQUENCE webapp.parent_forms_form_uid_seq RENAME TO forms_form_uid_seq;"
        )
        batch_op.execute(
            "ALTER SEQUENCE webapp.forms_form_uid_seq OWNED BY webapp.forms.form_uid;"
        )
        batch_op.alter_column(
            "form_uid",
            server_default=sa.text("nextval('webapp.forms_form_uid_seq'::regclass)"),
        )

        # Drop the unique constraints
        batch_op.drop_constraint(
            "_parent_forms_survey_uid_form_name_uc", type_="unique"
        )
        batch_op.drop_constraint(
            "_parent_forms_survey_uid_scto_form_id_uc", type_="unique"
        )

        # Recreate the unique constraints
        batch_op.create_unique_constraint(
            "_forms_survey_uid_form_name_uc", ["survey_uid", "form_name"]
        )
        batch_op.create_unique_constraint(
            "_forms_survey_uid_scto_form_id_uc", ["survey_uid", "scto_form_id"]
        )

        # Drop and recreate the foreign key constraint for surveys
        batch_op.drop_constraint(
            "fk_parent_forms_survey_uid_surveys", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_forms_survey_uid_surveys",
            "surveys",
            ["survey_uid"],
            ["survey_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

        # Create the foreign key constraint for parent_form_uid to form_uid
        batch_op.create_foreign_key(
            "fk_forms_parent_form_uid_forms",
            "forms",
            ["parent_form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    # Add the foreign key constraints back to the tables that reference the forms table
    with op.batch_alter_table("assignments_table_config", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_assignments_table_config_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("enumerator_column_config", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_enumerator_column_config_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("enumerators", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_enumerators_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("location_monitor_mapping", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_location_monitor_mapping_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("location_surveyor_mapping", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_location_surveyor_mapping_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("monitor_forms", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_monitor_forms_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("scto_form_choice_lists", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_scto_form_choice_lists_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scto_form_questions", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_scto_form_questions_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scto_form_settings", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_scto_form_settings_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scto_question_mapping", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_scto_question_mapping_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("surveyor_forms", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_surveyor_forms_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("surveyor_stats", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_surveyor_stats_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_target_column_config_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("targets", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_targets_form_uid_forms"),
            "forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("targets", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_targets_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_target_column_config_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("surveyor_stats", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_surveyor_stats_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("surveyor_forms", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_surveyor_forms_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("scto_question_mapping", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scto_question_mapping_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("scto_form_settings", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scto_form_settings_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("scto_form_questions", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scto_form_questions_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("scto_form_choice_lists", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_scto_form_choice_lists_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("monitor_forms", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_monitor_forms_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("location_surveyor_mapping", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_location_surveyor_mapping_form_uid_forms"),
            type_="foreignkey",
        )

    with op.batch_alter_table("location_monitor_mapping", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_location_monitor_mapping_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("enumerators", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_enumerators_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("enumerator_column_config", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_enumerator_column_config_form_uid_forms"), type_="foreignkey"
        )

    with op.batch_alter_table("assignments_table_config", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_assignments_table_config_form_uid_forms"), type_="foreignkey"
        )

    op.rename_table("parent_forms", "forms", schema="webapp")
    with op.batch_alter_table("forms", schema="webapp") as batch_op:
        batch_op.drop_column("form_type")
        batch_op.drop_column("dq_form_type")
        batch_op.drop_column("parent_form_uid")

        batch_op.drop_constraint("pk_forms", type_="primary")
        batch_op.create_primary_key("pk_parent_forms", ["form_uid"])

        # Rename the primary key sequence
        batch_op.execute(
            "ALTER SEQUENCE webapp.forms_form_uid_seq RENAME TO parent_forms_form_uid_seq;"
        )
        batch_op.execute(
            "ALTER SEQUENCE webapp.parent_forms_form_uid_seq OWNED BY webapp.parent_forms.form_uid;"
        )
        batch_op.alter_column(
            "form_uid",
            server_default=sa.text(
                "nextval('webapp.parent_forms_form_uid_seq'::regclass)"
            ),
        )

        # Drop the unique constraints
        batch_op.drop_constraint("_forms_survey_uid_form_name_uc", type_="unique")
        batch_op.drop_constraint("_forms_survey_uid_scto_form_id_uc", type_="unique")

        # Recreate the unique constraints
        batch_op.create_unique_constraint(
            "_parent_forms_survey_uid_form_name_uc", ["survey_uid", "form_name"]
        )
        batch_op.create_unique_constraint(
            "_parent_forms_survey_uid_scto_form_id_uc", ["survey_uid", "scto_form_id"]
        )

        # Drop and recreate the foreign key constraint for surveys
        batch_op.drop_constraint("fk_forms_survey_uid_surveys", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_parent_forms_survey_uid_surveys",
            "surveys",
            ["survey_uid"],
            ["survey_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("targets", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_targets_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("target_column_config", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_target_column_config_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("surveyor_stats", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_surveyor_stats_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("surveyor_forms", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_surveyor_forms_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("scto_question_mapping", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_scto_question_mapping_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scto_form_settings", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_scto_form_settings_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scto_form_questions", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_scto_form_questions_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("scto_form_choice_lists", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_scto_form_choice_lists_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("monitor_forms", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_monitor_forms_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("location_surveyor_mapping", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_location_surveyor_mapping_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("location_monitor_mapping", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_location_monitor_mapping_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("enumerators", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_enumerators_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("enumerator_column_config", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_enumerator_column_config_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    with op.batch_alter_table("assignments_table_config", schema="webapp") as batch_op:
        batch_op.create_foreign_key(
            "fk_assignments_table_config_form_uid_parent_forms",
            "parent_forms",
            ["form_uid"],
            ["form_uid"],
            referent_schema="webapp",
        )

    # ### end Alembic commands ###
