"""Add target status mapping tables

Revision ID: b8318c6eb036
Revises: 702360394ae3
Create Date: 2024-04-04 11:55:01.434770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8318c6eb036'
down_revision = '702360394ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_target_status_mapping',
    sa.Column(
        'surveying_method',
        sa.String(length=16),
        sa.CheckConstraint(
            "surveying_method IN ('phone', 'in-person', 'mixed-mode')",
            name="ck_default_target_status_mapping_surveying_method",
        ),
        nullable=False,
    ),
    sa.Column('survey_status', sa.Integer(), nullable=False),
    sa.Column('survey_status_label', sa.String(), nullable=False),
    sa.Column('completed_flag', sa.Boolean(), nullable=False),
    sa.Column('refusal_flag', sa.Boolean(), nullable=False),
    sa.Column('target_assignable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('webapp_tag_color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('surveying_method', 'survey_status', name=op.f('pk_default_target_status_mapping')),
    schema='webapp'
    )
    op.create_table('target_status_mapping',
    sa.Column('form_uid', sa.Integer(), nullable=False),
    sa.Column('survey_status', sa.Integer(), nullable=False),
    sa.Column('survey_status_label', sa.String(), nullable=False),
    sa.Column('completed_flag', sa.Boolean(), nullable=False),
    sa.Column('refusal_flag', sa.Boolean(), nullable=False),
    sa.Column('target_assignable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('webapp_tag_color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_uid'], ['webapp.parent_forms.form_uid'], name=op.f('fk_target_status_mapping_form_uid_parent_forms')),
    sa.PrimaryKeyConstraint('form_uid', 'survey_status', name=op.f('pk_target_status_mapping')),
    schema='webapp'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_status_mapping', schema='webapp')
    op.drop_table('default_target_status_mapping', schema='webapp')
    # ### end Alembic commands ###
