"""empty message

Revision ID: bb71e765ca9d
Revises: 4c32850b5077
Create Date: 2024-07-26 11:37:44.381704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb71e765ca9d'
down_revision = '4c32850b5077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('cc_users', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('pdf_attachment', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('pdf_encryption', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('pdf_encryption_password_type', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.drop_column('pdf_encryption_password_type')
        batch_op.drop_column('pdf_encryption')
        batch_op.drop_column('pdf_attachment')
        batch_op.drop_column('cc_users')

    # ### end Alembic commands ###
