"""Add DQ logic check assertions and questions tables

Revision ID: be5aa53fff5b
Revises: 6508381ec406
Create Date: 2025-01-17 09:47:12.912639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5aa53fff5b'
down_revision = '6508381ec406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dq_logic_check_assertions',
    sa.Column('assert_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dq_check_uid', sa.Integer(), nullable=False),
    sa.Column('assert_group_id', sa.Integer(), nullable=False),
    sa.Column('assertion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dq_check_uid'], ['webapp.dq_checks.dq_check_uid'], name=op.f('fk_dq_logic_check_assertions_dq_check_uid_dq_checks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assert_uid', name=op.f('pk_dq_logic_check_assertions')),
    schema='webapp'
    )
    op.create_table('dq_logic_check_questions',
    sa.Column('dq_check_uid', sa.Integer(), nullable=False),
    sa.Column('question_name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dq_check_uid'], ['webapp.dq_checks.dq_check_uid'], name=op.f('fk_dq_logic_check_questions_dq_check_uid_dq_checks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dq_check_uid', 'question_name', name=op.f('pk_dq_logic_check_questions')),
    sa.UniqueConstraint('dq_check_uid', 'alias', name='_dq_logic_check_questions_dq_check_uid_alias_uc'),
    schema='webapp'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dq_logic_check_questions', schema='webapp')
    op.drop_table('dq_logic_check_assertions', schema='webapp')
    # ### end Alembic commands ###
