"""Minor change to module_status table constraint to allow 'In Progress - Incomplete' status

Revision ID: bf0794f8d800
Revises: 3e80e9fc2452
Create Date: 2025-02-04 13:35:07.551592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0794f8d800'
down_revision = '3e80e9fc2452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_status', schema='webapp') as batch_op:
        # Add 'Live' to config_status options
        batch_op.drop_constraint('ck_module_status_config_status', type_='check')
        batch_op.create_check_constraint(
            "ck_module_status_config_status", sa.text("config_status IN ('Done','In Progress','In Progress - Incomplete','Not Started','Error','Live')",)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_status', schema='webapp') as batch_op:
        # Remove 'Live' from config_status options
        batch_op.drop_constraint('ck_module_status_config_status', type_='check')
        batch_op.create_check_constraint(
            "ck_module_status_config_status", sa.text("config_status IN ('Done','In Progress','Not Started', 'Error', 'Live')")
        )

    # ### end Alembic commands ###
