"""is_reuired column added to scto_form_questions

Revision ID: bfffe141e0f3
Revises: dbb88ef67228
Create Date: 2025-01-13 06:21:41.947334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfffe141e0f3'
down_revision = 'dbb88ef67228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_form_questions', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=True, server_default="false"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_form_questions', schema='webapp') as batch_op:
        batch_op.drop_column('is_required')

    # ### end Alembic commands ###
