"""Minor fix on the case of 'Is Empty' in check constraint for DQCheckFilters

Revision ID: c5530d333545
Revises: 631e9daa33d0
Create Date: 2025-05-27 04:07:12.464633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5530d333545'
down_revision = '631e9daa33d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_check_filters', schema='webapp') as batch_op:
        batch_op.drop_constraint(
            'ck_dq_check_filters_filter_operator',
            type_='check',
        )
        batch_op.create_check_constraint(
            "ck_dq_check_filters_filter_operator",
            """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is empty',
                'Is not empty',
                'Greater than',
                'Smaller than')""",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_check_filters', schema='webapp') as batch_op:
        batch_op.drop_constraint(
            'ck_dq_check_filters_filter_operator',
            type_='check',
        )
        batch_op.create_check_constraint(
            "ck_dq_check_filters_filter_operator",
            """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is Empty',
                'Is not empty',
                'Greater than',
                'Smaller than')""",
        )

    # ### end Alembic commands ###
