"""Add target_mapping_criteria column and rename supervisor_assignment_criteria to surveyor_mapping_criteria

Revision ID: c6731eec7e32
Revises: 4c32850b5077
Create Date: 2024-07-26 10:59:29.539482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6731eec7e32'
down_revision = '4c32850b5077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_questionnaire', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('target_mapping_criteria', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.alter_column('supervisor_assignment_criteria', nullable=True, new_column_name='surveyor_mapping_criteria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_questionnaire', schema='webapp') as batch_op:
        batch_op.alter_column('surveyor_mapping_criteria', nullable=True, new_column_name='supervisor_assignment_criteria')
        batch_op.drop_column('target_mapping_criteria')
        
    # ### end Alembic commands ###
