"""
Add CC usersm, PDF attachment and encryption to Email Configs

Revision ID: c8e211417f9b
Revises: c6731eec7e32
Create Date: 2024-07-26 12:16:31.562714

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8e211417f9b"
down_revision = "c6731eec7e32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_configs", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column("cc_users", sa.ARRAY(sa.Integer()), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "pdf_attachment", sa.Boolean(), server_default="false", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "pdf_encryption", sa.Boolean(), server_default="false", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "pdf_encryption_password_type",
                sa.String(length=16),
                sa.CheckConstraint(
                    "pdf_encryption_password_type IN ('Pattern','Password', NULL)",
                    name="ck_email_configs_pdf_encryption_password_type",
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("email_configs", schema="webapp") as batch_op:
        batch_op.drop_column("pdf_encryption_password_type")
        batch_op.drop_column("pdf_encryption")
        batch_op.drop_column("pdf_attachment")
        batch_op.drop_column("cc_users")

    # ### end Alembic commands ###
