"""Enumerators Language
Revert this to avoid failures on existing records
Will handle language validations on input

Revision ID: cf68d3dcd91e
Revises: 0a0ad04d278a
Create Date: 2024-02-12 09:11:07.698909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf68d3dcd91e'
down_revision = '0a0ad04d278a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enumerators', schema='webapp') as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enumerators', schema='webapp') as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
