"""empty message

Revision ID: d1d10486ab0a
Revises: bf548e097b10
Create Date: 2023-12-07 15:34:51.857715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d10486ab0a'
down_revision = 'bf548e097b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('permission_uid', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name')),
    schema='webapp'
    )
    op.create_table('invites',
    sa.Column('invite_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invite_code', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['webapp.users.user_uid'], name=op.f('fk_invites_user_uid_users')),
    sa.PrimaryKeyConstraint('invite_uid', name=op.f('pk_invites')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_invites_invite_code')),
    schema='webapp'
    )
    op.create_table('role_permissions',
    sa.Column('role_permissions_uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_uid', sa.Integer(), nullable=True),
    sa.Column('permission_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_uid'], ['webapp.permissions.permission_uid'], name=op.f('fk_role_permissions_permission_uid_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uid'], ['webapp.roles.role_uid'], name=op.f('fk_role_permissions_role_uid_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_permissions_uid', name=op.f('pk_role_permissions')),
    schema='webapp'
    )
    op.create_table('user_hierarchy',
    sa.Column('survey_uid', sa.Integer(), nullable=False),
    sa.Column('role_uid', sa.Integer(), nullable=True),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.Column('parent_user_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_uid'], ['webapp.users.user_uid'], name=op.f('fk_user_hierarchy_parent_user_uid_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uid'], ['webapp.roles.role_uid'], name=op.f('fk_user_hierarchy_role_uid_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_uid'], ['webapp.surveys.survey_uid'], name=op.f('fk_user_hierarchy_survey_uid_surveys')),
    sa.ForeignKeyConstraint(['user_uid'], ['webapp.users.user_uid'], name=op.f('fk_user_hierarchy_user_uid_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_uid', 'user_uid', name='user_hierarchy_pk'),
    schema='webapp'
    )
    with op.batch_alter_table('roles', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.ARRAY(sa.Integer()), nullable=True))

    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('roles', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_secure',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='webapp') as batch_op:
        batch_op.alter_column('password_secure',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_super_admin')
        batch_op.drop_column('roles')

    with op.batch_alter_table('roles', schema='webapp') as batch_op:
        batch_op.drop_column('permissions')

    op.drop_table('user_hierarchy', schema='webapp')
    op.drop_table('role_permissions', schema='webapp')
    op.drop_table('invites', schema='webapp')
    op.drop_table('permissions', schema='webapp')
    # ### end Alembic commands ###
