"""
Media files config table - Add format column to store wide/long format for output
and media_fields column to store the list of media fields for wide format

Revision ID: d4f5516ae358
Revises: 8b17cd15773c
Create Date: 2025-04-18 05:17:52.872677

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4f5516ae358"
down_revision = "8b17cd15773c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_files_config", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column("format", sa.String(), server_default="long", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "media_fields",
                sa.ARRAY(sa.String()),
                server_default="{}",
                nullable=True,
            )
        )
        batch_op.create_check_constraint(
            "ck_media_files_config_format",
            "format IN ('long','wide')",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_files_config", schema="webapp") as batch_op:
        batch_op.drop_constraint(
            "ck_media_files_config_format", type_="check", schema="webapp"
        )
        batch_op.drop_column("media_fields")
        batch_op.drop_column("format")

    # ### end Alembic commands ###
