"""Make revisit_section and survey_status columns nullable on question mapping table

Revision ID: d5b758a41d9f
Revises: b8b5153f25a3
Create Date: 2023-07-14 12:32:03.324717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b758a41d9f'
down_revision = 'b8b5153f25a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_question_mapping', schema='webapp') as batch_op:
        batch_op.alter_column('survey_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('revisit_section',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scto_question_mapping', schema='webapp') as batch_op:
        batch_op.alter_column('revisit_section',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('survey_status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
