"""
Add Email Schedules
Add Email Templates
Add Manual Email Triggers

Revision ID: d6208287bd69
Revises: 3393b5cc3f28
Create Date: 2024-04-02 05:38:50.617243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6208287bd69'
down_revision = '3393b5cc3f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_schedules',
    sa.Column('email_schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_uid', sa.Integer(), nullable=True),
    sa.Column('date', sa.ARRAY(sa.Date()), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('template_uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('email_schedule_id', name=op.f('pk_email_schedules')),
    sa.UniqueConstraint('form_uid', name=op.f('uq_email_schedules_form_uid'))
    )
    op.create_table('email_templates',
    sa.Column('email_template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('email_template_id', name=op.f('pk_email_templates'))
    )
    op.create_table('manual_email_triggers',
    sa.Column('manual_email_trigger_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_uid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('recipients', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('template_uid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('manual_email_trigger_id', name=op.f('pk_manual_email_triggers')),
    sa.UniqueConstraint('form_uid', name=op.f('uq_manual_email_triggers_form_uid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_email_triggers')
    op.drop_table('email_templates')
    op.drop_table('email_schedules')
    # ### end Alembic commands ###
