"""Add targets endpoints

Revision ID: d798277afc23
Revises: 92edc2e0b7a7
Create Date: 2023-08-18 00:31:22.140786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d798277afc23"
down_revision = "92edc2e0b7a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "target_column_config",
        sa.Column("form_uid", sa.Integer(), nullable=False),
        sa.Column("column_name", sa.String(), nullable=False),
        sa.Column(
            "column_type",
            sa.String(),
            sa.CheckConstraint(
                "column_type IN ('basic_details','custom_fields','location')",
                name="ck_enumerator_column_config_column_type",
            ),
            nullable=False,
        ),
        sa.Column("bulk_editable", sa.Boolean(), nullable=False),
        sa.Column("contains_pii", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_uid"],
            ["webapp.parent_forms.form_uid"],
            name=op.f("fk_target_column_config_form_uid_parent_forms"),
        ),
        sa.PrimaryKeyConstraint(
            "form_uid", "column_name", name=op.f("pk_target_column_config")
        ),
        schema="webapp",
    )
    op.create_table(
        "targets",
        sa.Column("target_uid", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("location_uid", sa.Integer(), nullable=True),
        sa.Column(
            "custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("form_uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_uid"],
            ["webapp.parent_forms.form_uid"],
            name=op.f("fk_targets_form_uid_parent_forms"),
        ),
        sa.ForeignKeyConstraint(
            ["location_uid"],
            ["webapp.locations.location_uid"],
            name=op.f("fk_targets_location_uid_locations"),
        ),
        sa.PrimaryKeyConstraint("target_uid", name=op.f("pk_targets")),
        sa.UniqueConstraint(
            "form_uid", "target_id", name="_targets_form_uid_target_id_uc"
        ),
        schema="webapp",
    )
    op.create_table(
        "target_status",
        sa.Column("target_uid", sa.Integer(), nullable=False),
        sa.Column("completed_flag", sa.Boolean(), nullable=True),
        sa.Column("refusal_flag", sa.Boolean(), nullable=True),
        sa.Column("num_attempts", sa.Integer(), nullable=True),
        sa.Column("last_attempt_survey_status", sa.Integer(), nullable=True),
        sa.Column("last_attempt_survey_status_label", sa.String(), nullable=True),
        sa.Column("target_assignable", sa.Boolean(), nullable=True),
        sa.Column("webapp_tag_color", sa.String(), nullable=True),
        sa.Column("revisit_sections", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_uid"],
            ["webapp.targets.target_uid"],
            name=op.f("fk_target_status_target_uid_targets"),
        ),
        sa.PrimaryKeyConstraint("target_uid", name=op.f("pk_target_status")),
        schema="webapp",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("target_status", schema="webapp")
    op.drop_table("targets", schema="webapp")
    op.drop_table("target_column_config", schema="webapp")
    # ### end Alembic commands ###
