"""empty message

Revision ID: dcfd7fd39aa5
Revises: 33b8ce72b8e9
Create Date: 2023-09-08 23:58:17.901890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfd7fd39aa5'
down_revision = '33b8ce72b8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enumerators', schema='webapp') as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enumerators', schema='webapp') as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
