"""Correct the typo in the check constraint for filter_operator

Revision ID: e2cd5f73ac59
Revises: 69c35c7db756
Create Date: 2025-01-15 10:38:15.963025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cd5f73ac59'
down_revision = '69c35c7db756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_check_filters', schema='webapp') as batch_op:
        batch_op.drop_constraint('ck_dq_check_filters_filter_operator', type_='check')
        batch_op.create_check_constraint(
            "ck_dq_check_filters_filter_operator",
            """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is Empty',
                'Is not empty',
                'Greater than',
                'Smaller than')""",
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dq_check_filters', schema='webapp') as batch_op:
        batch_op.drop_constraint('ck_dq_check_filters_filter_operator', type_='check')
        batch_op.create_check_constraint(
            "ck_dq_check_filters_filter_operator",
            """filter_operator IN 
            (   'Is',
                'Is not',
                'Contains',
                'Does not contain',
                'Is Empty',
                'Is not empty',
                'Greather than',
                'Smaller than')""",
        )

    # ### end Alembic commands ###
