"""empty message

Revision ID: ef5824c38a12
Revises: 46ba6d963fde
Create Date: 2024-06-11 05:03:57.930806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5824c38a12'
down_revision = '46ba6d963fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_status', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('final_survey_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_survey_status_label', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_status', schema='webapp') as batch_op:
        batch_op.drop_column('final_survey_status_label')
        batch_op.drop_column('final_survey_status')

    # ### end Alembic commands ###
