"""empty message

Revision ID: efe1162067b0
Revises: 0e0c398beec2
Create Date: 2024-06-05 16:33:05.098116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe1162067b0'
down_revision = '0e0c398beec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('report_users', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('email_source', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email_source_gsheet_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('email_source_tablename', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('email_source_columns', sa.ARRAY(sa.String(length=128)), nullable=True))

    with op.batch_alter_table('email_schedules', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('email_schedule_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_schedules', schema='webapp') as batch_op:
        batch_op.drop_column('email_schedule_name')

    with op.batch_alter_table('email_configs', schema='webapp') as batch_op:
        batch_op.drop_column('email_source_columns')
        batch_op.drop_column('email_source_tablename')
        batch_op.drop_column('email_source_gsheet_key')
        batch_op.drop_column('email_source')
        batch_op.drop_column('report_users')

    # ### end Alembic commands ###
