"""
Add targets_last_uploaded column to target_config

Revision ID: fe556647b9f2
Revises: 69c35c7db756
Create Date: 2025-01-14 08:28:01.515532

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe556647b9f2"
down_revision = "69c35c7db756"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_config", schema="webapp") as batch_op:
        batch_op.add_column(
            sa.Column("targets_last_uploaded", sa.TIMESTAMP(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("target_config", schema="webapp") as batch_op:
        batch_op.drop_column("targets_last_uploaded")

    # ### end Alembic commands ###
