"""Add final survey status columns in target_status table

Revision ID: ffd697df5ae0
Revises: 17605263ee63
Create Date: 2024-06-14 04:59:17.951049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd697df5ae0'
down_revision = '17605263ee63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_status', schema='webapp') as batch_op:
        batch_op.add_column(sa.Column('final_survey_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_survey_status_label', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_status', schema='webapp') as batch_op:
        batch_op.drop_column('final_survey_status_label')
        batch_op.drop_column('final_survey_status')

    # ### end Alembic commands ###
