# Create GitHub Action to run unit tests inside a Docker container
name: Run Unit Tests

on:
  push:
    branches:
      - dev
      - staging
      - production

  pull_request:
    branches:
      - "*"

jobs:
  UnitTest:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./.github/workflows
          mode: unittest

      - name: Build the Docker image
        run: docker build -f Dockerfile.api --rm --build-arg NAME=$BACKEND_NAME --build-arg PORT=$BACKEND_PORT --platform=linux/amd64 -t $BACKEND_NAME:$VERSION .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::${{ env.DEV_ACCOUNT }}:role/github-actions-role-flask-unittest"
          role-session-name: testingrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure output directory
        run: |
          mkdir -p /tmp/coverage
          chmod 777 /tmp/coverage

      - name: Run unit tests
        run: docker-compose -f docker-compose/docker-compose.test-unit.yml -f docker-compose/docker-compose.override-test-unit.yml run --rm api ;

      - name: Send coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/coverage/coverage.lcov
